### ISSUE TITLE
not able to select apk from device

### ISSUE THREAD

**Issue by AkshayJainG** [linkedin/qark#17]
Do you want to:
[1] Provide a path to an APK
[2] Pull an existing APK from the device?

Select an APK[0-140]: 134
INFO - Selected:134 /data/app/tv.android-1.apk
5167 KB/s (13440708 bytes in 2.539s)
INFO - Unpacking /root/Downloads/qark-master/temp/tv.android-1.apk
INFO - Zipfile: <zipfile.ZipFile object at 0x7ff00bc48510>
INFO - Extracted APK to /root/Downloads/qark-master/temp/tv.android-1/
INFO - Finding AndroidManifest.xml in /root/Downloads/qark-master/temp/tv.periscope.android-1
INFO - AndroidManifest.xml found
Traceback (most recent call last):
  File "qark.py", line 492, in <module>
    ap = axmlprinter.AXMLPrinter(open(mf, 'rb').read())
  File "/root/Downloads/qark-master/lib/axmlparserpy/axmlprinter.py", line 47, in __init__
    self.buff += "xmlns:%s=\"%s\"\n" % (self.axml.getNamespacePrefix(0), self.axml.getNamespaceUri(0))
  File "/root/Downloads/qark-master/lib/axmlparserpy/axmlparser.py", line 194, in getNamespacePrefix
    prefix = self.m_prefixuriL[ pos ][0]
IndexError: list index out of range

**Comment by SecBro1** [comment]
Thanks for reporting the issue.

The APK was pulled, based on the output.

It looks like it's choking on trying to parse/print the AndroidManifest.XML.

We have seen some issues in the past with certain UNICODE characters
breaking the parsing.

I'll see if I have any luck with the same APK, but in the meantime, have
you tried other APKs and if so, did you have the same issue?

**Comment by AkshayJainG** [comment]
With othe

**Comment by tushardalvi** [comment]
@AkshayJainG , Can you help provide a sample APK (or a link to the APK) that doesnt work for you. We will get this fixed in our upcoming release.

**Comment by tushardalvi** [comment]
@AkshayJainG, This issue is now resolved. We have updated the way we parse manifest files, and it should work with any APK. Please let us know if you are still able to reproduce this issue.

**Comment by securisec** [comment]
I am still seeing this issue. Looks like it goes into a loop and doesnt break out of it. Happens mostly with apps with foreign chars in there.
